## Day- of #30daysofpython

## Topic: Numpy

* Importing numpy
* Creating 1-Dimensional arrays
    * Basic Methods
        * shape(), size(), ndim(), len(), dtype()
* Creating 2-Dimensional arrays
* Creating 3-Dimensional arrays
* arange(), reshape() for 1-D arrays
* Accesing rows, columns for 2-D arrays
    * axis = 0 (rows)
    * axis = 1 (columns)
* Numpy
    * Built-in Methods
        * ones(), zeros(),linspace(),random(),full()
        * eye(), randint(), arange(),tile()
    

#### * 'ndarray' is a data structure in numpy.

### importing a numpy

In [1]:
import numpy as np   # 'np' is alias name of numpy
np.__version__       # Returns version of numpy installed

'1.20.1'

#### Difference between a list and a array?
* The elements in a list are of different datatypes.
* The elements in a array must be of same datatypes.

### Creating 1-Dimensional arrays

In [3]:
a = np.array([1,2,3,4,5,6])
print(a)                     #prints without commas because it is an array.
print(type(a))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


### Basic Methods
* a.shape------->Gives number of elements in form of tuple as (rows, columns) 
* np.size(a)-------->Gives total number of elements in an array
* len(a)------------>Gives no of rows in an array.
* a.ndim------------>Gives dimension of an array
* a.dtype----------->Gives datatype

In [6]:
a = np.array([1,2,3,4,5,6])
print(a.shape)
print(np.size(a))
print(a.ndim)
print(len(a))
print(a.dtype)

(6,)
6
1
6
int32


### Creating 2-Dimensional arrays

In [8]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)                     #prints without commas because it is an array.
print(type(b))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [9]:
print(b.shape)
print(np.size(b))
print(b.ndim)
print(len(b))
print(b.dtype)

(3, 3)
9
2
3
int32


In [11]:
c = np.array([['a','b','c'],['d','e','f'],['g','h','i']])
print(c)
print(type(c))
print(c.shape)
print(c.ndim)
print(len(c))
print(np.size(c))
print(c.dtype)

[['a' 'b' 'c']
 ['d' 'e' 'f']
 ['g' 'h' 'i']]
<class 'numpy.ndarray'>
(3, 3)
2
3
9
<U1


## Creating 3-Dimensional arrays

In [85]:
a = np.arange(24).reshape(2,3,4)

#'4' is no. of inner elements
#'3' is no. of rows(inner)
#'2' is no. of rows(outer) 

print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


### creating 1-D array using arange()

In [13]:
x = np.arange(10)
print(x)
print(type(x))
print(x.shape)
print(np.size(x))
print(x.ndim)
print(len(x))
print(x.dtype)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)
10
1
10
int32


## reshape()

* reshape() is used to change dimension of an array

In [19]:
x = np.arange(10)
print(x)
print(x.ndim)
print(x.shape)         # Returns 10
print(x.reshape(5,2))  # Numbers in reshape should be a multiple of 10

[0 1 2 3 4 5 6 7 8 9]
1
(10,)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [20]:
print(x.reshape(2,5))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [22]:
print(x.reshape(10,1))

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


##### For 2-D arrays:
* axis = 0 refers to rows
* axis = 1 refers to columns

In [23]:
z = np.arange(1,13).reshape(3,4)  #2 operations can be done
print(z)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [24]:
z.sum()  #Returns sum of all elements

78

In [25]:
np.sum(z)  #Returns sum of all elements same as above

78

## axis=0
* To get sum of elements row wise

In [26]:
np.sum(z,axis=0) 

array([15, 18, 21, 24])

In [28]:
z.sum(axis=0)

array([15, 18, 21, 24])

In [29]:
z.sum(0)

array([15, 18, 21, 24])

## axis=1
* To get sum of elements column wise

In [27]:
np.sum(z,axis=1) 

array([10, 26, 42])

In [30]:
z.sum(axis=1)

array([10, 26, 42])

In [31]:
z.sum(1)

array([10, 26, 42])

### Initialisation of arrays

In [32]:
a = np.array([1,2,3,4])
b = np.array((1,2,3,4))
print(a)
print(b)

[1 2 3 4]
[1 2 3 4]


### Built-in Methods
* np.ones()-->Gives an array contains element '1'.By default 'float' type
* np.zeros()->Gives an array contains element '0'.By default 'float' type
* np.linspace()-->By default 'float' type.
* np.random.random()-->Creates random elements. By default  'float'
* np.arange()---------->By default 'int' type.
* np.full()-->Creates constant array of any number. Default 'int' type
* np.tile()-->Repeats array in sequence. By default 'int' type
* np.eye()--->Gives Identity matrix. By default 'float' type
* np.randint()--->Gives random array with specified range.By default 'int'

## np.ones()

#### Examples

In [34]:
a = np.ones((3,4),dtype = int)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [35]:
a = np.ones((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [36]:
a = np.ones((3,4),dtype = bool)
print(a)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [37]:
a = np.ones((3,),dtype = int)
print(a)

[1 1 1]


## np.zeros()

#### Examples

In [38]:
a = np.zeros([6,],dtype = int)
print(a)

[0 0 0 0 0 0]


In [39]:
a = np.zeros([6,3],dtype = int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [58]:
a = np.zeros([3,6])
print(a)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [40]:
a = np.zeros([3,6],dtype = bool)
print(a)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]]


## np.random()

#### Examples

In [46]:
a = np.random.random((3,4))  # Prints random numbers
print(a)

[[0.00795665 0.75053939 0.54756169 0.45738548]
 [0.2800641  0.31087731 0.01137597 0.58245503]
 [0.95039207 0.07158704 0.86026893 0.87204745]]


In [52]:
a = np.random.random([3,4]) 
print(a)

[[0.59427745 0.85876797 0.99260858 0.15710751]
 [0.95286301 0.43089177 0.99192862 0.44462341]
 [0.15796977 0.31275427 0.31443691 0.14009058]]


## np.linspace()

#### Examples

In [56]:
a = np.linspace(3,6,5,dtype = int) 

# '3' & '6' is range of elements.
# '5' is number of elements

print(a)

[3 3 4 5 6]


In [57]:
a = np.linspace(3,6,5,dtype = float)
print(a)

[3.   3.75 4.5  5.25 6.  ]


In [59]:
a = np.linspace(3,6,5)
print(a)

[3.   3.75 4.5  5.25 6.  ]


## np.arange()

#### Examples

In [41]:
a = np.arange(1,6)
print(a)

[1 2 3 4 5]


In [45]:
a = np.arange(1,6,dtype=float)
print(a)

[1. 2. 3. 4. 5.]


## np.full()

#### Examples

In [63]:
a = np.full((3,4),8)

# (3,4) is (row,columns) & '8' is constant number

print(a)

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


In [64]:
a = np.full((3,4),'a')

# (3,4) is (row,columns) & 'a' is constant variable

print(a)

[['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']]


In [65]:
a = np.full((3,4),8,dtype = float)

# (3,4) is (row,columns) & '8' is constant number

print(a)

[[8. 8. 8. 8.]
 [8. 8. 8. 8.]
 [8. 8. 8. 8.]]


## n.tile()

#### Examples

In [67]:
a = np.array([1,2,3])
print(np.tile(a,3))

[1 2 3 1 2 3 1 2 3]


In [78]:
a = np.array([1,2,3])
print(np.tile(a,(3,2)))
#'a' is array.In (3,2) '3' is row size. '2' is repeating twice

[[1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]]


In [72]:
a = np.arange(1,7)
b = a.reshape(2,3)
c = np.tile(b,2)
print(c)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


## np.eye()

#### Example

In [75]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [76]:
a = np.eye(3,dtype = int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


## np.randint()

#### Examples

In [81]:
a = np.random.randint(1,6,(3,3))
print(a)

[[5 2 1]
 [4 3 2]
 [4 1 5]]


In [82]:
a = np.random.randint(1,9,(6,3))
print(a)

[[4 3 4]
 [8 2 1]
 [3 3 2]
 [5 4 1]
 [8 6 7]
 [3 2 2]]


* Difference b/w randint & random is: 
* random gives in b/w range of '0' & '1'. By default 'float'
* randint gives any range of elements. By default 'int'